apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop2
  labels:
    app: catalogue
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      tier: app
      project: roboshop
      environment: practice
  template:
    metadata:
      labels:
        app: catalogue
        tier: app
        project: roboshop
        environment: practice
    spec:
      containers:
      - name: catalogue
        image: hari9397/catalogue:v1.0.0
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    app: catalogue
    tier: app
    project: roboshop
    environment: practice
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 8080 # This port is related to service port
    targetPort: 8080 # This is related to Conatiner port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop2
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/users"
