apiVersion: v1
kind: Pod
metadata:
  name: image-pull
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: always
    resources:
      requests:
        cpu: "200m"
        memory: "128mi"
      limits:
        cpu: "210m"
        memory: "258mi"
