# FROM almalinux:8
# RUN yum install nginx -y
# RUN echo "Hello World" > /usr/share/nginx/html/hello.html
# CMD ["nginx", "-g", "daemon off;"]

#cmd and run command will run at the time of creating and running the containers


FROM almalinux
CMD ["/usr/bin/wc","--help"]