apiVersion: apps/v1
kind: Statefulset
metadata:
  name: mongodb
  labels:
    app: mongodb
    tier: db
    project: roboshop
spec:
  selector:
      matchLables:
          app: mongodb
          tier: db
          project: roboshop
  serviceName: "mongodb"
  replicas: 1
  template:
      metadata:
          name: roboshop
          labels:
              app: mongodb
              tier: db
              project: roboshop
      spec:
          containers:
          - name: mongodb
            image: joindevops/mongodb:1.0.0
            volumeMounts:
            - name: mongodb
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metatada:
  name: mongodb
spec:
  ClusterIP: none
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017
        
