apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    environment: production
    app: frontend
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - conatinerPort: 80
      name: 81
---
apiVersion: v1
kind: Service
metadata:
  name: service-conf1
spec:
  selector:
    environment: production
    app: frontend    
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 81