apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop2
  labels:
    environment: developement
    app: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: developement
      app: roboshop
      tier: db
  template:
    metadata:
      name: roboshop
      labels:
        environment: developement
        app: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: hari9397/mongodb:v1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    environment: developement
    tier: db
    app: roboshop
spec:
  selector:
    environment: developement
    app: roboshop
    tier: db
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017