apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-replica
  labels:
    name: replica1
    tier: frontend
spec:
  replicas: 3
  selector:
    matchlabels:
      tier: frontend
  template:
    metadata:
      name: pod-definition
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80


# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: replicaset
#   labels:
#     name: replicapodset
#     tier: frontend
# spec:
#   replicas: 3
#   selectors:
#     matchLabels:
#       name: nginx
#       tier: frontend
#   template:
#     metadata:
#       labels:
#         name: nginx
#         tier: frontend
#     spec:
#       containers:
#       - name: nginx
#         image: nginx
#         ports:
#         - containerPort: 80
