apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    environment: developement1
    tier: frontend1
    app: nginx1
  ports:
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: 80