apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
      environment: practice
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop
        environment: practice
    spec:
      containers:
      - name: mongodb
        image: hari9397/mongodb:1.0.0
--- 
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    tier: db
    project: roboshop
    environment: practice
  ports:
  - name: mongodb-roboshop
    protocol: TCP
    port: 27017 # This Port Belongs to Service
    targetPort: 27017 # This Port Belongs to the Container