FROM almalinux
RUN yum install nginx -y
EXPOSE 80/tcp
LABEL NAME="PEDDIREDDY"\
      YEAR="2023"\
      COURSE="2023"
ENV  NAME=Peddireddy\
     YEAR=2023\
     COURSE=DEVOPS 
CMD [ "nginx", "g", "deamon off;"]
