apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: roboshop
spec:
  containers:
  - name: nginx-i
    image: nginx
    ports:
    - containerPort: 80

# If we give name space it will append to the mentioned namespace else it will attach to the default namespace

# apiVersion: v1
# kind: Pod
# metadata:
#   name: git-install
#   namespace: roboshop
# spec:
#   containers:
#   - name: git install
#     image: git
#     ports:
#     - containerPort: 80
  