apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  namespace: roboshop
spec:
  containers:
  - name: nginx-install
    image: nginx
  - name: sidecar
    image: almalinux
    command: ["sleep 300"]
