apiVersion: v1
kind: Pod
metadata:
  name: config-direct
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: config-map
envFrom:
- configMapRef:
    name: config-map