apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    environment: development
    service: nginx-service
    app: front-end
  annotations:
    web.dev.com: hari
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    environment: development
    service: nginx-service
    app: front-end
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc